name: dart_box2d
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Youry <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  box2d_flame:
    git: 
      url: https://github.com/feroult/box2d.dart.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
